version: '3.8'

services:
  # The Spring Boot Application Service
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      # This tells the app to connect to the 'mongo' service below
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/kaiburr_task1
    depends_on:
      - mongo

  # The MongoDB Database Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

